### ISSUE TITLE
[Feature] 사용자 개인화

### ISSUE THREAD

**Issue by 4923** [VENCLFIT/watch-your-neck#3]
## TODO's
- [ ] 유저기능 구현 하면 flowchart 개편 필요
- [ ] URLrouting 설계 제대로 할 것 (페이지 목록 뽑히는대로)
- [ ] 상황에 따른 거북목지수 수치화 할 방법 마련 (JS로 결과값을 어떻게 뽑아와야하지...)

**Comment by 4923** [comment]
chrome extension 으로 넘어가며 임시 close
